<?php

$metadata = array(
    'theme_name' => 'Paper <span class="off">חדש</span>',
    'thumbnail_image' => 'https://i.websmaking.com/images/templates/preview/photo-4.png',
    'preview_image' => 'https://i.websmaking.com/images/templates/demo/photo-4.png',
    'folder_name' => 'Upload',
    'made_by' => '<a href="https://websmaking.com" style="font-weight:bold;">WebsMaking</a>',
    'data' => array( 
        'he' => array( 
            'css' => 'style.rtl.css?v=0.0.7',
            'header' => '<p><span style="font-size:72px;"><span style="color:#465268;">Paper</span></span></p>',
            'content' => '<table align="center" border="0" cellpadding="1" cellspacing="1" style="width:100%;"> <tbody> <tr> <td> <center><img alt="" src="https://i.websmaking.com/images/templates/photo-1527239441953-caffd968d952.jpg" style="height: 170px; width: 170px; position: relative;" /></center> <center><span style="font-size:20px;"><strong>הקלד/י כותרת</strong></span><br /> הקלידו משהו...הקלידו משהו...הקלידו משהו...הקלידו משהו...הקלידו משהו...הקלידו משהו...הקלידו משהו...הקלידו משהו...</center> </td> <td> <center><img alt="" src="https://i.websmaking.com/images/templates/photo-1527769929977-c341ee9f2033.jpg" style="height: 170px; width: 170px; position: relative;" /><br /> <span style="font-size:20px;"><strong>הקלד/י כותרת</strong></span><br /> הקלידו משהו...הקלידו משהו...הקלידו משהו...הקלידו משהו...הקלידו משהו...הקלידו משהו...הקלידו משהו...הקלידו משהו...</center> </td> <td> <center><img alt="" src="https://i.websmaking.com/images/templates/photo-1450101499163-c8848c66ca85.jpg" style="height: 170px; width: 170px; position: relative;" /></center> <center><span style="font-size:20px;"><strong>הקלד/י כותרת</strong></span><br /> הקלידו משהו...הקלידו משהו...הקלידו משהו...הקלידו משהו...הקלידו משהו...הקלידו משהו...הקלידו משהו...הקלידו משהו...</center> </td> </tr> <tr> <td> <p><br /> <em><strong><span style="font-size:22px;">כותרת פסקה</span></strong></em></p> <p>הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...</p> </td> <td> <p><br /> <em><strong><span style="font-size:22px;">כותרת פסקה</span></strong></em></p> <p>הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...</p> </td> <td> <p><br /> <em><strong><span style="font-size:22px;">כותרת פסקה</span></strong></em></p> <p>הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...הקלידו כאן משהו...</p> </td> </tr> </tbody> </table>',
            'footer' => '<p style="text-align: center;">Paper נוצר ב-&hearts; ע&quot;י WebsMaking.com</p>',
            'sidebar' => '<table align="center" border="0" cellpadding="1" cellspacing="1" style="width:100%;"> <tbody> <tr> <td style="width: 30%;"><img src="https://i.websmaking.com/images/templates/photo-1565545389759-1616edd6003a.jpg" style="position: relative; border-radius: 10px; height: 100px; width: 100px;" /></td> <td style="width: 70%;"><span style="font-size:20px;"><strong>&nbsp;הקלד שם כאן</strong></span></td> </tr> <tr> <td colspan="2"> <table align="center" border="0" cellpadding="1" cellspacing="1"> <tbody> <tr> <td> <hr /> <p>הקלידו כאן משהו, כל דבר שמדבר עליכם או על העסק שלכם, שיוכל למשוך גולשים לאתר וכ&#39;ו...הקלידו כאן משהו, כל דבר שמדבר עליכם או על העסק שלכם, שיוכל למשוך גולשים לאתר וכ&#39;ו...הקלידו כאן משהו, כל דבר שמדבר עליכם או על העסק שלכם, שיוכל למשוך גולשים לאתר וכ&#39;ו...הקלידו כאן משהו, כל דבר שמדבר עליכם או על העסק שלכם, שיוכל למשוך גולשים לאתר וכ&#39;ו...הקלידו כאן משהו, כל דבר שמדבר עליכם או על העסק שלכם, שיוכל למשוך גולשים לאתר וכ&#39;ו...הקלידו כאן משהו, כל דבר שמדבר עליכם או על העסק שלכם, שיוכל למשוך גולשים לאתר וכ&#39;ו...</p> </td> </tr> </tbody> </table> </td> </tr> </tbody> </table>',
            'created_by' => 'WebsMaking בניית אתרים',
            'main_page_caption' => 'דף ראשי'
            ),
        'en' => array( 
            'css' => 'style.ltr.css',
            'header' => '<p><span style="font-size:72px;"><span style="color:#465268;">Paper</span></span></p>',
            'content' => '<table align="center" border="0" cellpadding="1" cellspacing="1" style="width:100%;"> <tbody> <tr> <td> <center><img alt="" src="https://i.websmaking.com/images/templates/photo-1527239441953-caffd968d952.jpg" style="height: 170px; width: 170px; position: relative;" /></center> <center><span style="font-size:20px;"><strong>Type title</strong></span><br /> Some text..Some text..Some text..Some text..Some text..Some text..Some text..Some text..</center> </td> <td> <center><img alt="" src="https://i.websmaking.com/images/templates/photo-1527769929977-c341ee9f2033.jpg" style="height: 170px; width: 170px; position: relative;" /><br /> <span style="font-size:20px;"><strong>Type title</strong></span><br /> Some text..Some text..Some text..Some text..Some text..Some text..Some text..Some text..</center> </td> <td> <center><img alt="" src="https://i.websmaking.com/images/templates/photo-1450101499163-c8848c66ca85.jpg" style="height: 170px; width: 170px; position: relative;" /></center> <center><span style="font-size:20px;"><strong>Type title</strong></span><br /> Some text..Some text..Some text..Some text..Some text..Some text..Some text..Some text..</center> </td> </tr> <tr> <td> <p><br /> <em><strong><span style="font-size:22px;">Type title</span></strong></em></p> <p>Some text to enable scrolling.. Lorem ipsum dolor sit amet, illum definitiones no quo, maluisset concludaturque et eum, altera fabulas ut quo. Atqui causae gloriatur ius te, id agam omnis evertitur eum. Affert laboramus repudiandae nec et. Inciderint efficiantur his ad. Eum no molestiae voluptatibus.</p> </td> <td> <p><br /> <em><strong><span style="font-size:22px;">Type title</span></strong></em></p> <p>Some text to enable scrolling.. Lorem ipsum dolor sit amet, illum definitiones no quo, maluisset concludaturque et eum, altera fabulas ut quo. Atqui causae gloriatur ius te, id agam omnis evertitur eum. Affert laboramus repudiandae nec et. Inciderint efficiantur his ad. Eum no molestiae voluptatibus.</p> </td> <td> <p><br /> <em><strong><span style="font-size:22px;">Type title</span></strong></em></p> <p>Some text to enable scrolling.. Lorem ipsum dolor sit amet, illum definitiones no quo, maluisset concludaturque et eum, altera fabulas ut quo. Atqui causae gloriatur ius te, id agam omnis evertitur eum. Affert laboramus repudiandae nec et. Inciderint efficiantur his ad. Eum no molestiae voluptatibus.</p> </td> </tr> </tbody> </table>',
            'footer' => '<p style="text-align: center;">Paper made with &hearts; by WebsMaking.com</p>',
            'sidebar' => '<table align="center" border="0" cellpadding="1" cellspacing="1" style="width:100%;"> <tbody> <tr> <td style="width: 30%;"><img src="https://i.websmaking.com/images/templates/photo-1565545389759-1616edd6003a.jpg" style="position: relative; border-radius: 10px; height: 100px; width: 100px;" /></td> <td style="width: 70%;"><span style="font-size:20px;"><strong>&nbsp;Type name here</strong></span></td> </tr> <tr> <td colspan="2"> <table align="center" border="0" cellpadding="1" cellspacing="1"> <tbody> <tr> <td> <hr /> <p>Some text to enable scrolling.. Lorem ipsum dolor sit amet, illum definitiones no quo, maluisset concludaturque et eum, altera fabulas ut quo. Atqui causae gloriatur ius te, id agam omnis evertitur eum. Affert laboramus repudiandae nec et. Inciderint efficiantur his ad. Eum no molestiae voluptatibus.</p> </td> </tr> </tbody> </table> </td> </tr> </tbody> </table>',
            'created_by' => 'WebsMaking Website Building',
            'main_page_caption' => 'Home page'
            )
        )
    );

?>