<?php

$metadata = array(
    'theme_name' => 'template1',
    'thumbnail_image' => 'https://i.websmaking.com/images/templates/preview/photo-7.png',
    'preview_image' => 'https://i.websmaking.com/images/templates/demo/photo-7.png',
    'folder_name' => 'AwesomeBlue',
    'made_by' => '<a href="https://websmaking.com" style="font-weight:bold;">WebsMaking</a>',
    'data' => array( 
        'he' => array( 
            'css' => 'style.rtl.css',
            'header' => '<p><img src="https://i.imgur.com/EWRBmot.png" style="width: 100%; margin-top: -16px;" /></p>',
            'content' => '<style type="text/css">.box { box-shadow: 0px 0px 15px 0px rgba(0, 0, 0, 0.75); float: right; padding: 10px; margin-bottom: 2em; } </style> <div class="box"> <h3><img alt="" src="https://images.unsplash.com/photo-1524496686051-f9b8e8cf9d1a?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1000&amp;q=80" style="margin-right: 10px; float: left; width: 50%;" />הטיול הגדול עם החברה הטובה</h3> <p>Some text to enable scrolling.. Lorem ipsum dolor sit amet, illum definitiones no quo, maluisset concludaturque et eum, altera fabulas ut quo. Atqui causae gloriatur ius te, id agam omnis evertitur eum. Affert laboramus repudiandae nec et. Inciderint efficiantur his ad. Eum no molestiae voluptatibus.</p> <p><input name="more" type="button" value="ראה/י עוד" /></p> </div> <div class="box"> <h3><img alt="" src="https://images.unsplash.com/photo-1520645521318-f03a712f0e67?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1350&amp;q=80" style="margin-right: 10px; float: left; width: 50%;" />משוטטת בלב העיר</h3> <p>Some text to enable scrolling.. Lorem ipsum dolor sit amet, illum definitiones no quo, maluisset concludaturque et eum, altera fabulas ut quo. Atqui causae gloriatur ius te, id agam omnis evertitur eum. Affert laboramus repudiandae nec et. Inciderint efficiantur his ad. Eum no molestiae voluptatibus.</p> <p><input name="more" type="button" value="ראה/י עוד" /></p> </div> <div class="box"> <h3><img alt="" src="https://images.unsplash.com/photo-1467922688251-c3011eac929a?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1350&amp;q=80" style="margin-right: 10px; float: left; width: 50%;" />רכיבה על סוסים עם המשפחה!</h3> <p>Some text to enable scrolling.. Lorem ipsum dolor sit amet, illum definitiones no quo, maluisset concludaturque et eum, altera fabulas ut quo. Atqui causae gloriatur ius te, id agam omnis evertitur eum. Affert laboramus repudiandae nec et. Inciderint efficiantur his ad. Eum no molestiae voluptatibus.</p> <p><input name="more" type="button" value="ראה/י עוד" /></p> </div>',
            'footer' => '<div dir="rtl" style="text-shadow: 0px 0px 12px #000;"> <p style="text-align: center;"><span style="color:#ffffff;"><span style="font-size: 20px;">&copy; כל הזכויות שמורות</span></span></p> </div>',
            'sidebar' => '<style type="text/css">.button { border: none; outline: 0; display: inline-block; padding: 8px; color: white; background-color: #4CAF50; text-align: center; cursor: pointer; width: 100%; } .button:hover { background-color: #555; } </style> <p><img alt="" src="https://images.unsplash.com/photo-1509828399123-6e6b9355dd01?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1225&amp;q=80" style="max-width: 100%; width: 100%;" /></p> <div class="container"> <h2>מסביב לעולם</h2> <p>Some text that describes me lorem ipsum ipsum lorem.</p> <p>example@example.com</p> <p><button class="button">יצירת קשר</button></p> </div>',
            'created_by' => 'WebsMaking בניית אתרים',
            'main_page_caption' => 'דף ראשי'
            ),
        'en' => array( 
            'css' => 'style.ltr.css',
            'header' => '<p><img src="https://i.imgur.com/EWRBmot.png" style="width: 100%; margin-top: -16px;" /></p>',
            'content' => '<style type="text/css">.box { box-shadow: 0px 0px 15px 0px rgba(0, 0, 0, 0.75); float: right; padding: 10px; margin-bottom: 2em; } </style> <div class="box"> <h3><img alt="" src="https://images.unsplash.com/photo-1524496686051-f9b8e8cf9d1a?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1000&amp;q=80" style="margin-right: 10px; float: left; width: 50%;" />My Best Trip</h3> <p>Some text to enable scrolling.. Lorem ipsum dolor sit amet, illum definitiones no quo, maluisset concludaturque et eum, altera fabulas ut quo. Atqui causae gloriatur ius te, id agam omnis evertitur eum. Affert laboramus repudiandae nec et. Inciderint efficiantur his ad. Eum no molestiae voluptatibus.</p> <p><input name="more" type="button" value="See More" /></p> </div> <div class="box"> <h3><img alt="" src="https://images.unsplash.com/photo-1520645521318-f03a712f0e67?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1350&amp;q=80" style="margin-right: 10px; float: left; width: 50%;" />I&#39;m going to the center of the city</h3> <p>Some text to enable scrolling.. Lorem ipsum dolor sit amet, illum definitiones no quo, maluisset concludaturque et eum, altera fabulas ut quo. Atqui causae gloriatur ius te, id agam omnis evertitur eum. Affert laboramus repudiandae nec et. Inciderint efficiantur his ad. Eum no molestiae voluptatibus.</p> <p><input name="more" type="button" value="See More" /></p> </div> <div class="box"> <h3><img alt="" src="https://images.unsplash.com/photo-1467922688251-c3011eac929a?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1350&amp;q=80" style="margin-right: 10px; float: left; width: 50%;" />Horseback riding with my family</h3> <p>Some text to enable scrolling.. Lorem ipsum dolor sit amet, illum definitiones no quo, maluisset concludaturque et eum, altera fabulas ut quo. Atqui causae gloriatur ius te, id agam omnis evertitur eum. Affert laboramus repudiandae nec et. Inciderint efficiantur his ad. Eum no molestiae voluptatibus.</p> <p><input name="more" type="button" value="See More" /></p> </div>',
            'footer' => '<div dir="ltr" style="    text-shadow: 0px 0px 12px #000;"> <p style="text-align: center;"><span style="color:#ffffff;"><span style="font-size: 20px;">&copy; All Rights Reserved</span></span></p> </div>',
            'sidebar' => '<style type="text/css">.button { border: none; outline: 0; display: inline-block; padding: 8px; color: white; background-color: #4CAF50; text-align: center; cursor: pointer; width: 100%; } .button:hover { background-color: #555; } </style> <p><img alt="" src="https://images.unsplash.com/photo-1509828399123-6e6b9355dd01?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1225&amp;q=80" style="max-width: 100%; width: 100%;" /></p> <div class="container"> <h2>Around the world</h2> <p>Some text that describes me lorem ipsum ipsum lorem.</p> <p>example@example.com</p> <p><button class="button">Contact</button></p> </div>',
            'created_by' => 'WebsMaking Website Building',
            'main_page_caption' => 'Home page'
            )
        )
    );

?>