<?php

$metadata = array(
    'theme_name' => 'Aline | Beauty & Power',
    'thumbnail_image' => 'https://i.websmaking.com/images/templates/preview/photo-2.png',
    'preview_image' => 'https://i.websmaking.com/images/templates/demo/photo-2.png?v=0.1',
    'folder_name' => 'Aline',
    'made_by' => '<a href="https://websmaking.com" style="font-weight:bold;">WebsMaking</a>',
    'data' => array( 
        'he' => array( 
            'css' => 'style.rtl.css',
            'header' => '<table border="0" cellpadding="1" cellspacing="1" style="width:100%;"> 	<tbody> 		<tr> 			<td> 			<h1><span style="font-size:36px;"><strong><span style="font-family:Times New Roman,Times,serif;">YOUR CUSTOM LOGO</span></strong></span></h1> 			</td> 			<td> 			<h2>תיאור האתר כאן<br /> 			<span style="font-size:16px;">על מה העסק שלך עוסק?</span></h2> 			</td> 			<td><img alt="" src="https://image.flaticon.com/icons/png/512/33/33702.png" style="height: 30px; width: 30px;" />&nbsp;<img alt="" src="https://image.flaticon.com/icons/png/512/23/23931.png" style="height: 30px; width: 30px;" />&nbsp;<img alt="" src="https://image.flaticon.com/icons/png/512/25/25178.png" style="height: 30px; width: 30px;" /></td> 		</tr> 	</tbody> </table>',
            'content' => '<style type="text/css">.img-home{ width:100%; height: 100%; position:relative; background-image:url(https://images.unsplash.com/photo-1454391304352-2bf4678b1a7a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80); background-size:cover; background-position:50%; } .img-home:before{ content:""; position: absolute; left: 2%; top: 2%; width: 95%; height: 95%; border: 1px solid white; } </style> <div class="img-home" style="text-align: center;"><br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <strong><span style="font-size:36px;"><span style="color:#000000;"><span style="background-color:#ffffff;">שם העסק שלך כאן</span></span></span></strong><br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> &nbsp;</div> <table align="right" border="0" cellpadding="1" cellspacing="1" style="width:100%;"> <tbody> <tr> <td style="text-align: center;"> <p><img alt="" class="ie-container" src="https://images.unsplash.com/photo-1501438400798-b40ff50396c8?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1350&amp;q=80" style="width: 100%;" /><br /> <span style="font-size:22px;"><strong>ניתן לשנות טקסט זה בקלות</strong></span><br /> <span style="font-size:18px;">תשנו את הטקסט הזה בחופשיות<br /> <input name="bottun" type="button" value="כפתור" /></span></p> </td> <td> <p style="text-align: center;"><img alt="" class="ie-container" src="https://images.unsplash.com/photo-1501438400798-b40ff50396c8?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1350&amp;q=80" style="width: 100%;" /><br /> <span style="font-size:22px;"><strong>ניתן לשנות טקסט זה בקלות</strong></span><br /> <span style="font-size:18px;">תשנו את הטקסט הזה בחופשיות<br /> <input name="button" type="button" value="כפתור" /></span></p> </td> <td style="text-align: center;"> <p><img alt="" class="ie-container" src="https://images.unsplash.com/photo-1501438400798-b40ff50396c8?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1350&amp;q=80" style="width: 100%;" /><br /> <span style="font-size:22px;"><strong>ניתן לשנות טקסט זה בקלות</strong></span><br /> <span style="font-size:18px;">תשנו את הטקסט הזה בחופשיות<br /> <input name="bottun" type="button" value="כפתור" /></span></p> </td> </tr> </tbody> </table>',
            'footer' => '<p style="text-align: center;"><img alt="" src="https://image.flaticon.com/icons/png/512/33/33702.png" style="height: 30px; width: 30px;" />&nbsp;<img alt="" src="https://image.flaticon.com/icons/png/512/23/23931.png" style="height: 30px; width: 30px;" />&nbsp;<img alt="" src="https://image.flaticon.com/icons/png/512/25/25178.png" style="height: 30px; width: 30px;" /></p>  <p style="text-align: center;">&copy; כל הזכויות שמורות</p>',
            'sidebar' => '<p><strong><span style="font-size:24px;">החלק הצידי לא נתמך בתבנית זו.</span></strong></p>',
            'created_by' => 'WebsMaking בניית אתרים',
            'main_page_caption' => 'דף ראשי'
            ),
        'en' => array( 
            'css' => 'style.ltr.css',
            'header' => '<table border="0" cellpadding="1" cellspacing="1" style="width:100%;"> <tbody> <tr> <td> <h1><span style="font-size:36px;"><strong><span style="font-family:Times New Roman,Times,serif;">YOUR CUSTOM LOGO</span></strong></span></h1> </td> <td> <h2>Site description here<br /> <span style="font-size:16px;">What is your business about?</span></h2> </td> <td><img alt="" src="https://image.flaticon.com/icons/png/512/33/33702.png" style="height: 30px; width: 30px;" />&nbsp;<img alt="" src="https://image.flaticon.com/icons/png/512/23/23931.png" style="height: 30px; width: 30px;" />&nbsp;<img alt="" src="https://image.flaticon.com/icons/png/512/25/25178.png" style="height: 30px; width: 30px;" /></td> </tr> </tbody> </table>',
            'content' => '<style type="text/css">.img-home{ width:100%; height: 100%; position:relative; background-image:url(https://images.unsplash.com/photo-1454391304352-2bf4678b1a7a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80); background-size:cover; background-position:50%; } .img-home:before{ content:""; position: absolute; left: 2%; top: 2%; width: 95%; height: 95%; border: 1px solid white; } </style> <div class="img-home" style="text-align: center;"><br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <strong><span style="font-size:36px;"><span style="color:#000000;"><span style="background-color:#ffffff;">Name of the business</span></span></span></strong><br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> &nbsp;</div> <table align="right" border="0" cellpadding="1" cellspacing="1" style="width:100%;"> <tbody> <tr> <td style="text-align: center;"> <p><img alt="" class="ie-container" src="https://images.unsplash.com/photo-1501438400798-b40ff50396c8?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1350&amp;q=80" style="width: 100%;" /><br /> <span style="font-size:22px;"><strong>You can change this text</strong></span><br /> <span style="font-size:18px;">Edit this text freely,&nbsp;Edit this text freely<br /> <input name="bottun" type="button" value="Button" /></span></p> </td> <td> <p style="text-align: center;"><img alt="" class="ie-container" src="https://images.unsplash.com/photo-1501438400798-b40ff50396c8?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1350&amp;q=80" style="width: 100%;" /><br /> <span style="font-size:22px;"><strong>You can change this text</strong></span><br /> <span style="font-size:18px;">Edit this text freely,&nbsp;Edit this text freely<br /> <input name="button" type="button" value="Button" /></span></p> </td> <td style="text-align: center;"> <p><img alt="" class="ie-container" src="https://images.unsplash.com/photo-1501438400798-b40ff50396c8?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1350&amp;q=80" style="width: 100%;" /><br /> <span style="font-size:22px;"><strong>You can change this text</strong></span><br /> <span style="font-size:18px;">Edit this text freely,&nbsp;Edit this text free<br /> <input name="bottun" type="button" value="Button" /></span></p> </td> </tr> </tbody> </table>',
            'footer' => '<p dir="ltr" style="text-align: center;"><img alt="" src="https://image.flaticon.com/icons/png/512/33/33702.png" style="height: 30px; width: 30px;" />&nbsp;<img alt="" src="https://image.flaticon.com/icons/png/512/23/23931.png" style="height: 30px; width: 30px;" />&nbsp;<img alt="" src="https://image.flaticon.com/icons/png/512/25/25178.png" style="height: 30px; width: 30px;" /></p> <p dir="ltr" style="text-align: center;">&copy; All rights reserved</p>',
            'sidebar' => '<p><strong><span style="font-size:24px;">The sidebar is not supported in this template.</span></strong></p>',
            'created_by' => 'WebsMaking Website Building',
            'main_page_caption' => 'Home page'
            )
        )
    );

?>