<?php

$metadata = array(
    'theme_name' => 'Creative',
    'thumbnail_image' => 'https://i.websmaking.com/images/templates/preview/photo-9.png',
    'preview_image' => 'https://i.websmaking.com/images/templates/demo/photo-9.png',
    'folder_name' => 'Creative',
    'made_by' => '<a href="https://websmaking.com" style="font-weight:bold;">WebsMaking</a>',
    'data' => array( 
        'he' => array( 
            'css' => 'style.rtl.css',
            'header' => '<a href="#">Your Logo</a>',
            'content' => '<img height="800px" src="https://images.unsplash.com/photo-1469334031218-e382a71b716b?ixlib=rb-1.2.1&amp;auto=format&amp;fit=crop&amp;w=1350&amp;q=80" style="object-fit: cover;" width="100%" /> <h2 class="myH2"><span style="color:#e74c3c;">הערה:</span><span style="color:#999999;"> הוסף תמונה לפני כל טקסט ביצירת דף חדש.</span></h2> <h2 class="myH2">מה אנחנו עושים?</h2> <p class="myP">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsum ratione facere animi impedit rem labore sint repellendus ipsa sapiente voluptatem aut excepturi quo itaque, ab earum cumque. Voluptatem beatae id inventore quod voluptate qui deserunt, quis placeat, tempora ex totam, dolore sequi harum eos voluptatibus animi labore officiis minus laboriosam Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsum ratione facere animi impedit rem labore sint repellendus ipsa sapiente voluptatem aut excepturi quo itaque, ab earum cumque. Voluptatem beatae id inventore quod voluptate qui deserunt, quis placeat, tempora ex totam, dolore sequi harum eos voluptatibus animi labore officiis minus laboriosam Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsum ratione facere animi impedit rem labore sint repellendus ipsa sapiente voluptatem aut excepturi quo itaque, ab earum cumque. Voluptatem beatae id inventore quod voluptate qui deserunt, quis placeat, tempora ex totam, dolore sequi harum eos voluptatibus animi labore officiis minus laboriosam Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsum ratione facere animi impedit rem labore sint repellendus ipsa sapiente voluptatem aut excepturi quo itaque, ab earum cumque. Voluptatem beatae id inventore quod voluptate qui deserunt, quis placeat, tempora ex totam, dolore sequi harum eos voluptatibus animi labore officiis minus laboriosam Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsum ratione facere animi impedit rem labore sint repellendus ipsa sapiente voluptatem aut excepturi quo itaque, ab earum cumque. Voluptatem beatae id inventore quod voluptate qui deserunt, quis placeat, tempora ex totam, dolore sequi harum eos voluptatibus animi labore officiis minus laboriosam</p> <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script><script src="js/scripts.js"></script><script> $(window).scroll(function() { if ($(document).scrollTop() > 50) { $(".nav").addClass("affix"); console.log("OK"); } else { $(".nav").removeClass("affix"); } }); </script><script src="https://static.codepen.io/assets/common/stopExecutionOnTimeout-9bf952ccbbd13c245169a0a1190323a27ce073a3d304b8c0fdf421ab22794a58.js"></script><script id="rendered-js"> $(".navTrigger").click(function () { $(this).toggleClass("active"); console.log("Clicked menu"); $("#mainListDiv").toggleClass("show_list"); $("#mainListDiv").fadeIn(); }); //# sourceURL=pen.js </script>',
            'footer' => '<style type="text/css">footer { width: 100%; display: inline-block; margin: 2em 0; height: 70px; background-color: #999; } footer .copyright { width: 50%; float: left; } @media (max-width: 600px) { footer .copyright { width: 100%; } } footer .copyright p { padding-left: 10%; color: white; font-size: 0.7em; line-height: 70px; text-transform: capitalize; letter-spacing: 1px; } @media (max-width: 600px) { footer .copyright p { text-align: center; padding: 0; } } footer .social { width: 50%; float: right; } @media (max-width: 600px) { footer .social { width: 100%; } } footer .social a { float: left; line-height: 70px; text-decoration: none; color: white; text-align: center; font-weight: bold; -moz-transition: all, 0.3s; -o-transition: all, 0.3s; -webkit-transition: all, 0.3s; transition: all, 0.3s; } footer .social a:hover { background-color: #222; -moz-transition: all, 0.3s; -o-transition: all, 0.3s; -webkit-transition: all, 0.3s; transition: all, 0.3s; } .linked { background-color: #1E83AE; font-size: 1.2em; width: 20%; } .face { background-color: #3D5B94; font-size: 1.2em; width: 20%; } .tweet { background-color: #3DACDD; font-size: 1.2em; width: 20%; } .support { background-color: #6dcd9a; font-size: 0.8em; width: 40%; } </style> <footer> <div class="copyright"> <p><span style="font-size:20px;">&nbsp; &nbsp;&copy; כל הזכויות שמורות</span></p> </div> <div class="social"><span style="font-size:20px;"><a class="support" href="mailto:mail@websmaking.com">צור קשר</a></span> <span style="font-size:20px;"><a class="face" href="#">f</a> <a class="tweet" href="#">t</a> <a class="linked" href="#">in</a></span></div> </footer>',
            'sidebar' => '<strong><span style="font-size:24px;">חלק צידי אינו נתמך בתבנית זו.</span></strong>',
            'created_by' => 'WebsMaking בניית אתרים',
            'main_page_caption' => 'דף ראשי'
            ),
        'en' => array( 
            'css' => 'style.ltr.css',
            'header' => '<a href="#">Your Logo</a>',
            'content' => '<img height="800px" src="https://images.unsplash.com/photo-1469334031218-e382a71b716b?ixlib=rb-1.2.1&amp;auto=format&amp;fit=crop&amp;w=1350&amp;q=80" style="object-fit: cover;" width="100%" /> <h2 class="myH2"><span style="color:#e74c3c;">Note:</span><span style="color:#999999;"> </span><span style="color:#999999;">Add an image before each text on a new page.</span></h2> <h2 class="myH2">What is this?</h2> <p class="myP">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsum ratione facere animi impedit rem labore sint repellendus ipsa sapiente voluptatem aut excepturi quo itaque, ab earum cumque. Voluptatem beatae id inventore quod voluptate qui deserunt, quis placeat, tempora ex totam, dolore sequi harum eos voluptatibus animi labore officiis minus laboriosam Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsum ratione facere animi impedit rem labore sint repellendus ipsa sapiente voluptatem aut excepturi quo itaque, ab earum cumque. Voluptatem beatae id inventore quod voluptate qui deserunt, quis placeat, tempora ex totam, dolore sequi harum eos voluptatibus animi labore officiis minus laboriosam Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsum ratione facere animi impedit rem labore sint repellendus ipsa sapiente voluptatem aut excepturi quo itaque, ab earum cumque. Voluptatem beatae id inventore quod voluptate qui deserunt, quis placeat, tempora ex totam, dolore sequi harum eos voluptatibus animi labore officiis minus laboriosam Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsum ratione facere animi impedit rem labore sint repellendus ipsa sapiente voluptatem aut excepturi quo itaque, ab earum cumque. Voluptatem beatae id inventore quod voluptate qui deserunt, quis placeat, tempora ex totam, dolore sequi harum eos voluptatibus animi labore officiis minus laboriosam Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsum ratione facere animi impedit rem labore sint repellendus ipsa sapiente voluptatem aut excepturi quo itaque, ab earum cumque. Voluptatem beatae id inventore quod voluptate qui deserunt, quis placeat, tempora ex totam, dolore sequi harum eos voluptatibus animi labore officiis minus laboriosam</p> <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script><script src="js/scripts.js"></script><script> $(window).scroll(function() { if ($(document).scrollTop() > 50) { $(".nav").addClass("affix"); console.log("OK"); } else { $(".nav").removeClass("affix"); } }); </script><script src="https://static.codepen.io/assets/common/stopExecutionOnTimeout-9bf952ccbbd13c245169a0a1190323a27ce073a3d304b8c0fdf421ab22794a58.js"></script><script id="rendered-js"> $(".navTrigger").click(function () { $(this).toggleClass("active"); console.log("Clicked menu"); $("#mainListDiv").toggleClass("show_list"); $("#mainListDiv").fadeIn(); }); //# sourceURL=pen.js </script>',
            'footer' => '<style type="text/css">footer { width: 100%; display: inline-block; margin: 2em 0; height: 70px; background-color: #999; } footer .copyright { width: 50%; float: left; } @media (max-width: 600px) { footer .copyright { width: 100%; } } footer .copyright p { padding-left: 10%; color: white; font-size: 0.7em; line-height: 70px; text-transform: capitalize; letter-spacing: 1px; } @media (max-width: 600px) { footer .copyright p { text-align: center; padding: 0; } } footer .social { width: 50%; float: right; } @media (max-width: 600px) { footer .social { width: 100%; } } footer .social a { float: left; line-height: 70px; text-decoration: none; color: white; text-align: center; font-weight: bold; -moz-transition: all, 0.3s; -o-transition: all, 0.3s; -webkit-transition: all, 0.3s; transition: all, 0.3s; } footer .social a:hover { background-color: #222; -moz-transition: all, 0.3s; -o-transition: all, 0.3s; -webkit-transition: all, 0.3s; transition: all, 0.3s; } .linked { background-color: #1E83AE; font-size: 1.2em; width: 20%; } .face { background-color: #3D5B94; font-size: 1.2em; width: 20%; } .tweet { background-color: #3DACDD; font-size: 1.2em; width: 20%; } .support { background-color: #6dcd9a; font-size: 0.8em; width: 40%; } </style> <footer> <div class="copyright"> <p><span style="font-size:20px;">&copy; All Right Saved</span></p> </div> <div class="social"><span style="font-size:20px;"><a class="support" href="mailto:mail@websmaking.com">Contact Us</a></span> <span style="font-size:20px;"><a class="face" href="#">f</a> <a class="tweet" href="#">t</a> <a class="linked" href="#">in</a></span></div> </footer>',
            'sidebar' => '<strong><span style="font-size:24px;">The sidebar is not supported in this template.</span></strong>',
            'created_by' => 'WebsMaking Website Building',
            'main_page_caption' => 'Home page'
            )
        )
    );

?>