<?php

$metadata = array(
    'theme_name' => 'Classic | Default',
    'thumbnail_image' => 'https://i.websmaking.com/images/templates/preview/photo.png',
    'preview_image' => 'https://i.websmaking.com/images/templates/demo/photo.png',
    'folder_name' => 'Classic',
    'made_by' => '<a href="https://websmaking.com" style="font-weight:bold;">WebsMaking</a>',
    'data' => array( 
        'he' => array( 
            'css' => 'style.rtl.css?v=0.0.9',
            'header' => '<table border="0" cellpadding="1" cellspacing="1" style="width:100%;"> 	<tbody> 		<tr> 			<td> 			<h1><span style="font-size:36px;"><strong><span style="font-family:Times New Roman,Times,serif;">YOUR CUSTOM LOGO</span></strong></span></h1> 			</td> 			<td> 			<h2>תיאור האתר כאן<br /> 			<span style="font-size:16px;">על מה העסק שלך עוסק?</span></h2> 			</td> 			<td><img alt="" src="https://image.flaticon.com/icons/png/512/33/33702.png" style="height: 30px; width: 30px;" />&nbsp;<img alt="" src="https://image.flaticon.com/icons/png/512/23/23931.png" style="height: 30px; width: 30px;" />&nbsp;<img alt="" src="https://image.flaticon.com/icons/png/512/25/25178.png" style="height: 30px; width: 30px;" /></td> 		</tr> 	</tbody> </table>',
            'content' => '<table align="center" border="0" cellpadding="1" cellspacing="1" style="width:100%;"> 	<tbody> 		<tr> 			<td> 			<p style="text-align: center;"><img alt="" src="https://images.unsplash.com/photo-1513151233558-d860c5398176?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1350&amp;q=80" style="width: 100%; float: right;" /><span style="font-size:36px;"><span style="color:#2980b9;"><strong>ברכות על אתרך החדש!</strong></span></span><br /> 			<span style="font-size:22px;"><span style="color:#e67e22;"><strong>כעת ניתן לצור תוכן ואפילו לערוך טקסט זה באמצעות פאנל ניהולך, בהצלחה! :)</strong></span></span><br /> 			<span style="font-size:18px;">טקסט זה ניתן להחלפה בעזרת פאנל המנהלים, תערכו את זה למה שתרצו.&nbsp;טקסט זה ניתן להחלפה בעזרת פאנל המנהלים, תערכו את זה למה שתרצו.&nbsp;</span><span style="font-size:18px;">טקסט זה ניתן להחלפה בעזרת פאנל המנהלים, תערכו את זה למה שתרצו.&nbsp;</span><span style="font-size:18px;">טקסט זה ניתן להחלפה בעזרת פאנל המנהלים, תערכו את זה למה שתרצו.&nbsp;</span><span style="font-size:18px;">טקסט זה ניתן להחלפה בעזרת פאנל המנהלים, תערכו את זה למה שתרצו.&nbsp;</span><span style="font-size:18px;">טקסט זה ניתן להחלפה בעזרת פאנל המנהלים, תערכו את זה למה שתרצו.&nbsp;</span><span style="font-size:18px;">טקסט זה ניתן להחלפה בעזרת פאנל המנהלים, תערכו את זה למה שתרצו.&nbsp;</span><span style="font-size:18px;">טקסט זה ניתן להחלפה בעזרת פאנל המנהלים, תערכו את זה למה שתרצו.&nbsp;</span><span style="font-size:18px;">טקסט זה ניתן להחלפה בעזרת פאנל המנהלים, תערכו את זה למה שתרצו.&nbsp;</span><span style="font-size:18px;">טקסט זה ניתן להחלפה בעזרת פאנל המנהלים, תערכו את זה למה שתרצו.&nbsp;</span><span style="font-size:18px;">טקסט זה ניתן להחלפה בעזרת פאנל המנהלים, תערכו את זה למה שתרצו.&nbsp;</span><span style="font-size:18px;">טקסט זה ניתן להחלפה בעזרת פאנל המנהלים, תערכו את זה למה שתרצו.&nbsp;</span><span style="font-size:18px;">טקסט זה ניתן להחלפה בעזרת פאנל המנהלים, תערכו את זה למה שתרצו.&nbsp;</span><span style="font-size:18px;">טקסט זה ניתן להחלפה בעזרת פאנל המנהלים, תערכו את זה למה שתרצו.&nbsp;</span><span style="font-size:18px;">טקסט זה ניתן להחלפה בעזרת פאנל המנהלים</span></p>  			<p style="text-align: center;"><span style="font-size:18px;"><input name="כפתור" type="button" value="כפתור לעריכה" /></span></p> 			</td> 		</tr> 	</tbody> </table>',
            'footer' => '<p style="text-align: center;"><img alt="" src="https://image.flaticon.com/icons/png/512/33/33702.png" style="height: 30px; width: 30px;" />&nbsp;<img alt="" src="https://image.flaticon.com/icons/png/512/23/23931.png" style="height: 30px; width: 30px;" />&nbsp;<img alt="" src="https://image.flaticon.com/icons/png/512/25/25178.png" style="height: 30px; width: 30px;" /></p>  <p style="text-align: center;">&copy; כל הזכויות שמורות</p>',
            'sidebar' => '<p><strong>אפשרי לשנות את החלק הזה כפי שתרצו או לחילופין להעלים אותו.</strong></p>

<p><em>אפשרי לשנות את החלק הזה כפי שתרצו או לחילופין להעלים אותו.</em></p>

<p><strong>אפשרי לשנות את החלק הזה כפי שתרצו או לחילופין להעלים אותו.</strong></p>

<p><em>אפשרי לשנות את החלק הזה כפי שתרצו או לחילופין להעלים אותו.</em></p>

<p><strong>אפשרי לשנות את החלק הזה כפי שתרצו או לחילופין להעלים אותו.</strong></p>
',
            'created_by' => 'WebsMaking בניית אתרים',
            'main_page_caption' => 'דף ראשי'
            ),
        'en' => array( 
            'css' => 'style.ltr.css',
            'header' => '<table border="0" cellpadding="1" cellspacing="1" style="width:100%;"> <tbody> <tr> <td> <h1><span style="font-size:36px;"><strong><span style="font-family:Times New Roman,Times,serif;">YOUR CUSTOM LOGO</span></strong></span></h1> </td> <td> <h2>Site description here<br /> <span style="font-size:16px;">What is your business about?</span></h2> </td> <td><img alt="" src="https://image.flaticon.com/icons/png/512/33/33702.png" style="height: 30px; width: 30px;" />&nbsp;<img alt="" src="https://image.flaticon.com/icons/png/512/23/23931.png" style="height: 30px; width: 30px;" />&nbsp;<img alt="" src="https://image.flaticon.com/icons/png/512/25/25178.png" style="height: 30px; width: 30px;" /></td> </tr> </tbody> </table>',
            'content' => '<table align="center" border="0" cellpadding="1" cellspacing="1" style="width:100%;"> <tbody> <tr> <td> <p style="text-align: center;"><img alt="" src="https://images.unsplash.com/photo-1513151233558-d860c5398176?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1350&amp;q=80" style="width: 100%; float: right;" /><span style="font-size:36px;"><span style="color:#2980b9;"><strong>Congratulations for your new site!</strong></span></span><br /> <span style="font-size:22px;"><span style="color:#e67e22;"><strong>You can now create content and even edit this text with your admin panel, good luck! :)</strong></span></span><br /> <span style="font-size: 18px;">This text can be exchanged through the admin panel, make it what you want.&nbsp;</span><span style="font-size: 18px;">This text can be exchanged through the admin panel, make it what you want.&nbsp;</span><span style="font-size: 18px;">This text can be exchanged through the admin panel, make it what you want.&nbsp;</span><span style="font-size: 18px;">This text can be exchanged through the admin panel, make it what you want.&nbsp;</span><span style="font-size: 18px;">This text can be exchanged through the admin panel, make it what you want.&nbsp;</span><span style="font-size: 18px;">This text can be exchanged through the admin panel, make it what you want.&nbsp;</span><span style="font-size: 18px;">This text can be exchanged through the admin panel, make it what you want.&nbsp;</span><span style="font-size: 18px;">This text can be exchanged through the admin panel, make it what you want.&nbsp;</span><span style="font-size: 18px;">This text can be exchanged through the admin panel, make it what you want.&nbsp;</span><span style="font-size: 18px;">This text can be exchanged through the admin panel, make it what you want.&nbsp;This text can be exchanged through the admin panel, make it what you want.&nbsp;</span><span style="font-size: 18px;">This text can be exchanged through the admin panel, make it what you want.&nbsp;This text can be exchanged through the admin panel, make it what you want.&nbsp;</span></p> <p style="text-align: center;"><span style="font-size:18px;"><input name="button" type="button" value="Button" /></span></p> </td> </tr> </tbody> </table>',
            'footer' => '<p dir="ltr" style="text-align: center;"><img alt="" src="https://image.flaticon.com/icons/png/512/33/33702.png" style="height: 30px; width: 30px;" />&nbsp;<img alt="" src="https://image.flaticon.com/icons/png/512/23/23931.png" style="height: 30px; width: 30px;" />&nbsp;<img alt="" src="https://image.flaticon.com/icons/png/512/25/25178.png" style="height: 30px; width: 30px;" /></p> <p dir="ltr" style="text-align: center;">&copy; All rights reserved</p>',
            'sidebar' => '<p><strong>It is possible to change this sidebar as you wish or alternatively to hide it.</strong></p>',
            'created_by' => 'WebsMaking Website Building',
            'main_page_caption' => 'Home page'
            )
        )
    );

?>