<?php

$metadata = array(
    'theme_name' => 'Technology',
    'thumbnail_image' => 'https://i.websmaking.com/images/templates/preview/photo-3.png',
    'preview_image' => 'https://i.websmaking.com/images/templates/demo/photo-3.png',
    'folder_name' => 'Technology',
    'made_by' => '<a href="https://websmaking.com" style="font-weight:bold;">WebsMaking</a>',
    'data' => array( 
        'he' => array( 
            'css' => 'style.rtl.css',
            'header' => '<table border="0" cellpadding="1" cellspacing="1" style="width:100%;"> <tbody> <tr> <td><span style="color:#565c63;"><span style="font-family:Arimo,sans-serif;"><span style="font-size:36px;"><strong>Technology</strong></span></span></span></td> <td> <h2><span style="color:#7b8794;">תיאור האתר שלך יכנס לכאן<br /> <span style="font-size:18px;">על מה העסק שלך מדבר?</span></span></h2> </td> <td><a href="https://www.facebook.com" target="_blank"><img alt="" src="https://i1.wp.com/www.cafelapalma.com/wp-content/uploads/2015/12/facebook-logo-grey.png?ssl=1" style="height: 30px; width: 28px;" /></a>&nbsp;<a href="https://twitter.com" target="_blank"><img alt="" src="https://icon-library.net/images/white-twitter-icon/white-twitter-icon-26.jpg" style="height: 30px; width: 30px;" /></a>&nbsp;<a href="https://www.youtube.com" target="_blank"><img alt="" src="https://www.sociedadespanolaheridas.com/~josepr37/sociedades/seher/images/site/YoutubeGris2.png" style="height: 30px; width: 30px;" /></a></td> </tr> </tbody> </table>',
            'content' => '<style type="text/css">.box1 { background: url(https://i.websmaking.com/images/templates/photo-1556656793-08538906a9f8.jpg); margin-top: -25px; padding-top: 225px; text-align: center; color: #fff; font-size: 40px; font-weight: bold; padding-bottom: 225px; background-size: cover; background-repeat: no-repeat; background-position: 50% 50%; } .box2 { background: url(https://i.websmaking.com/images/templates/photo-1528254609158-ae7dfaa48ab3.jpg); text-align: center; padding-top: 260px; padding-bottom: 260px; font-size: 35px; font-weight: bold; background-size: cover; background-repeat: no-repeat; background-position: 50% 50%; } .box1-small { background: url(https://i.websmaking.com/images/templates/photo-1529448155365-b176d2c6906b.jpg); width: 50%; padding-top: 225px; padding-bottom: 225px; background-size: cover; background-repeat: no-repeat; background-position: 50% 50%; text-align: center; font-size: 29px; color: #fff; font-weight: bold; float: right; } .box2-small { background: url(https://i.websmaking.com/images/templates/photo-1542549237432-a176cb9d5e5e.jpg); width: 50%; padding-top: 225px; padding-bottom: 225px; background-size: cover; background-repeat: no-repeat; background-position: 50% 50%; text-align: center; font-size: 29px; color: #fff; font-weight: bold; float: left; } .inside-content { padding: 0px; } .content { width: auto; } </style> <div class="box1"><span style="color:#000000;">גלו עולם שלם של טכנולוגיה!<br /> <span style="font-size:28px;">הכנס טקסט כאן...</span></span></div> <div class="box2">ניתן לערוך תיאור זה על פי רצונך<br /> <input name="Read more..." type="button" value="קרא/י עוד" /></div> <div class="box1-small">צפו במבצעים שלנו<br /> <br /> <input name="Details" type="button" value="לפרטים נוספים" /></div> <div class="box2-small">טכנולוגיה בכף היד<br /> <br /> <input name="Details" type="button" value="מצא עכשיו!" /></div>',
            'footer' => '<p style="text-align: center;"><a href="https://www.facebook.com" target="_blank"><img alt="" src="https://i1.wp.com/www.cafelapalma.com/wp-content/uploads/2015/12/facebook-logo-grey.png?ssl=1" style="height: 30px; width: 28px;" /></a>&nbsp;<a href="https://twitter.com" target="_blank"><img alt="" src="https://icon-library.net/images/white-twitter-icon/white-twitter-icon-26.jpg" style="height: 30px; width: 30px;" /></a>&nbsp;<a href="https://www.youtube.com" target="_blank"><img alt="" src="https://www.sociedadespanolaheridas.com/~josepr37/sociedades/seher/images/site/YoutubeGris2.png" style="height: 30px; width: 30px;" /></a></p> <p style="text-align: center;">&copy; כל הזכויות שמורות</p>',
            'sidebar' => '<p><strong>אפשרי לשנות את החלק הזה כפי שתרצו או לחילופין להעלים אותו.</strong></p>

<p><em>אפשרי לשנות את החלק הזה כפי שתרצו או לחילופין להעלים אותו.</em></p>

<p><strong>אפשרי לשנות את החלק הזה כפי שתרצו או לחילופין להעלים אותו.</strong></p>

<p><em>אפשרי לשנות את החלק הזה כפי שתרצו או לחילופין להעלים אותו.</em></p>

<p><strong>אפשרי לשנות את החלק הזה כפי שתרצו או לחילופין להעלים אותו.</strong></p>
',
            'created_by' => 'WebsMaking בניית אתרים',
            'main_page_caption' => 'דף ראשי'
            ),
        'en' => array( 
            'css' => 'style.ltr.css',
            'header' => '<table border="0" cellpadding="1" cellspacing="1" style="width:100%;"> <tbody> <tr> <td><span style="color:#565c63;"><span style="font-family:Arimo,sans-serif;"><span style="font-size:36px;"><strong>Technology</strong></span></span></span></td> <td> <h2><span style="color:#7b8794;">Site description here<br /> <span style="font-size:18px;">What is your business about?</span></span></h2> </td> <td><a href="https://www.facebook.com" target="_blank"><img alt="" src="https://i1.wp.com/www.cafelapalma.com/wp-content/uploads/2015/12/facebook-logo-grey.png?ssl=1" style="height: 30px; width: 28px;" /></a>&nbsp;<a href="https://twitter.com" target="_blank"><img alt="" src="https://icon-library.net/images/white-twitter-icon/white-twitter-icon-26.jpg" style="height: 30px; width: 30px;" /></a>&nbsp;<a href="https://www.youtube.com" target="_blank"><img alt="" src="https://www.sociedadespanolaheridas.com/~josepr37/sociedades/seher/images/site/YoutubeGris2.png" style="height: 30px; width: 30px;" /></a></td> </tr> </tbody> </table>',
            'content' => '<style type="text/css">.box1 { background: url(https://i.websmaking.com/images/templates/photo-1556656793-08538906a9f8.jpg); margin-top: -25px; padding-top: 225px; text-align: center; color: #fff; font-size: 40px; font-weight: bold; padding-bottom: 225px; background-size: cover; background-repeat: no-repeat; background-position: 50% 50%; } .box2 { background: url(https://i.websmaking.com/images/templates/photo-1528254609158-ae7dfaa48ab3.jpg); text-align: center; padding-top: 260px; padding-bottom: 260px; font-size: 35px; font-weight: bold; background-size: cover; background-repeat: no-repeat; background-position: 50% 50%; } .box1-small { background: url(https://i.websmaking.com/images/templates/photo-1529448155365-b176d2c6906b.jpg); width: 50%; padding-top: 225px; padding-bottom: 225px; background-size: cover; background-repeat: no-repeat; background-position: 50% 50%; text-align: center; font-size: 29px; color: #fff; font-weight: bold; float: right; } .box2-small { background: url(https://i.websmaking.com/images/templates/photo-1542549237432-a176cb9d5e5e.jpg); width: 50%; padding-top: 225px; padding-bottom: 225px; background-size: cover; background-repeat: no-repeat; background-position: 50% 50%; text-align: center; font-size: 29px; color: #fff; font-weight: bold; float: left; } .inside-content { padding: 0px; } .content { width: auto; } </style> <div class="box1"><span style="color:#000000;">Discover a whole world of technology!<br /> <span style="font-size:28px;">Enter text here...</span></span></div> <div class="box2">This description can be edited<br /> <input name="Read more..." type="button" value="Read more" /></div> <div class="box1-small">Watch our offers<br /> <br /> <input name="Details" type="button" value="More details" /></div> <div class="box2-small">Technology at hand<br /> <br /> <input name="Details" type="button" value="Find now!" /></div>',
            'footer' => '<p style="text-align: center;"><a href="https://www.facebook.com" target="_blank"><img alt="" src="https://i1.wp.com/www.cafelapalma.com/wp-content/uploads/2015/12/facebook-logo-grey.png?ssl=1" style="height: 30px; width: 28px;" /></a>&nbsp;<a href="https://twitter.com" target="_blank"><img alt="" src="https://icon-library.net/images/white-twitter-icon/white-twitter-icon-26.jpg" style="height: 30px; width: 30px;" /></a>&nbsp;<a href="https://www.youtube.com" target="_blank"><img alt="" src="https://www.sociedadespanolaheridas.com/~josepr37/sociedades/seher/images/site/YoutubeGris2.png" style="height: 30px; width: 30px;" /></a></p> <p style="text-align: center;">&copy; All rights reserved</p>',
            'sidebar' => '<p><strong>It is possible to change this sidebar as you wish or alternatively to hide it.</strong></p>',
            'created_by' => 'WebsMaking Website Building',
            'main_page_caption' => 'Home page'
            )
        )
    );

?>